
server:  port: 8888
  
spring:
  cloud:    config:      server:
        encrypt:          enabled: false        git:
          uri: https://github.com/ThiagoSousaSantana/microservices-repo
          search-paths: fornecedor, loja, transportador